### EX.5

In [ ]:
import numpy as np
import numpy.linalg as la

In [ ]:
np.random.seed(314)
A = np.random.normal(size=(20,10))
b = np.random.normal(size=(20,))
c = 0.1 * np.random.normal(size=(10,))

In [ ]:
def f(x):
  return np.sqrt(1 + la.norm(A@x + b)**2) + c@x
def g(x):
  return (1/(np.sqrt(1 + la.norm(A@x + b)**2)))* A.T@(A@x + b) + c

In [ ]:
def gradient_method_backtracking(f, g, x0, s, alpha, beta, epsilon):
  x = x0
  grad = g(x)
  fun_val = f(x)
  iter = 0
  while la.norm(grad) > epsilon:
    iter = iter + 1
    t = s
    while fun_val - f(x- t*grad) < alpha * t * (la.norm(grad)**2):
      t = beta * t
    x = x - t*grad
    fun_val = f(x)
    grad = g(x)
    print('iter_number = {0:3d}'.format(iter), \
          'norm_grad = {0:2.6f}'.format(la.norm(grad)), \
          'fun_val = {0:2.6f}'.format(fun_val))
  return x, fun_val


In [ ]:
x0 = np.zeros((10,))
e = 10**-5

In [ ]:
gradient_method_backtracking(f,g,x0,0.01,0.5,0.5,e)

iter_number =   1 norm_grad = 3.154267 fun_val = 3.535844
iter_number =   2 norm_grad = 2.886510 fun_val = 3.440574
iter_number =   3 norm_grad = 2.637377 fun_val = 3.360865
iter_number =   4 norm_grad = 2.410547 fun_val = 3.294325
iter_number =   5 norm_grad = 2.207966 fun_val = 3.238690
iter_number =   6 norm_grad = 2.029989 fun_val = 3.191936
iter_number =   7 norm_grad = 1.875685 fun_val = 3.152324
iter_number =   8 norm_grad = 1.743209 fun_val = 3.118413
iter_number =   9 norm_grad = 1.630163 fun_val = 3.089036
iter_number =  10 norm_grad = 1.533915 fun_val = 3.063267
iter_number =  11 norm_grad = 1.451839 fun_val = 3.040384
iter_number =  12 norm_grad = 1.381484 fun_val = 3.019830
iter_number =  13 norm_grad = 1.320669 fun_val = 3.001175
iter_number =  14 norm_grad = 1.267527 fun_val = 2.984093
iter_number =  15 norm_grad = 1.220506 fun_val = 2.968331
iter_number =  16 norm_grad = 1.178348 fun_val = 2.953696
iter_number =  17 norm_grad = 1.140050 fun_val = 2.940040
iter_number = 

(array([-0.62746978, -0.10556081,  0.08648618,  0.00124894,  0.06208924,
        -0.17584324, -0.02114767, -0.10405328, -0.11558017, -0.01649848]),
 2.698515142445387)

In [ ]:
gradient_method_backtracking(f,g,x0,0.1,0.5,0.5,e)

iter_number =   1 norm_grad = 1.919580 fun_val = 3.194835
iter_number =   2 norm_grad = 1.292814 fun_val = 2.962738
iter_number =   3 norm_grad = 0.946429 fun_val = 2.844614
iter_number =   4 norm_grad = 0.703124 fun_val = 2.779366
iter_number =   5 norm_grad = 0.524613 fun_val = 2.743368
iter_number =   6 norm_grad = 0.393330 fun_val = 2.723638
iter_number =   7 norm_grad = 0.297063 fun_val = 2.712819
iter_number =   8 norm_grad = 0.226522 fun_val = 2.706839
iter_number =   9 norm_grad = 0.174617 fun_val = 2.703483
iter_number =  10 norm_grad = 0.136150 fun_val = 2.701562
iter_number =  11 norm_grad = 0.107351 fun_val = 2.700436
iter_number =  12 norm_grad = 0.085550 fun_val = 2.699759
iter_number =  13 norm_grad = 0.068839 fun_val = 2.699340
iter_number =  14 norm_grad = 0.055876 fun_val = 2.699075
iter_number =  15 norm_grad = 0.045700 fun_val = 2.698902
iter_number =  16 norm_grad = 0.037624 fun_val = 2.698786
iter_number =  17 norm_grad = 0.031151 fun_val = 2.698708
iter_number = 

(array([-0.62746978, -0.10556092,  0.08648664,  0.0012493 ,  0.0620891 ,
        -0.17584349, -0.02114756, -0.10405335, -0.11558045, -0.01649845]),
 2.6985151424384974)

In [ ]:
gradient_method_backtracking(f,g,x0,0.2,0.5,0.5,e)

iter_number =   1 norm_grad = 1.919580 fun_val = 3.194835
iter_number =   2 norm_grad = 1.292814 fun_val = 2.962738
iter_number =   3 norm_grad = 0.946429 fun_val = 2.844614
iter_number =   4 norm_grad = 0.703124 fun_val = 2.779366
iter_number =   5 norm_grad = 0.524613 fun_val = 2.743368
iter_number =   6 norm_grad = 0.393330 fun_val = 2.723638
iter_number =   7 norm_grad = 0.297063 fun_val = 2.712819
iter_number =   8 norm_grad = 0.226522 fun_val = 2.706839
iter_number =   9 norm_grad = 0.174617 fun_val = 2.703483
iter_number =  10 norm_grad = 0.136150 fun_val = 2.701562
iter_number =  11 norm_grad = 0.107351 fun_val = 2.700436
iter_number =  12 norm_grad = 0.085550 fun_val = 2.699759
iter_number =  13 norm_grad = 0.068839 fun_val = 2.699340
iter_number =  14 norm_grad = 0.055876 fun_val = 2.699075
iter_number =  15 norm_grad = 0.045700 fun_val = 2.698902
iter_number =  16 norm_grad = 0.037624 fun_val = 2.698786
iter_number =  17 norm_grad = 0.031151 fun_val = 2.698708
iter_number = 

(array([-0.62746978, -0.10556105,  0.08648717,  0.00124972,  0.06208893,
        -0.17584379, -0.02114745, -0.10405343, -0.11558079, -0.0164984 ]),
 2.6985151424313516)

In [ ]:
gradient_method_backtracking(f,g,x0,1,0.5,0.5,e)

iter_number =   1 norm_grad = 1.595748 fun_val = 3.131151
iter_number =   2 norm_grad = 1.173838 fun_val = 2.908159
iter_number =   3 norm_grad = 0.975082 fun_val = 2.805444
iter_number =   4 norm_grad = 0.583273 fun_val = 2.764459
iter_number =   5 norm_grad = 0.297395 fun_val = 2.709260
iter_number =   6 norm_grad = 0.177814 fun_val = 2.705542
iter_number =   7 norm_grad = 0.126141 fun_val = 2.700408
iter_number =   8 norm_grad = 0.068050 fun_val = 2.699795
iter_number =   9 norm_grad = 0.061400 fun_val = 2.699017
iter_number =  10 norm_grad = 0.033318 fun_val = 2.698873
iter_number =  11 norm_grad = 0.031797 fun_val = 2.698676
iter_number =  12 norm_grad = 0.018611 fun_val = 2.698635
iter_number =  13 norm_grad = 0.017039 fun_val = 2.698570
iter_number =  14 norm_grad = 0.010939 fun_val = 2.698558
iter_number =  15 norm_grad = 0.014370 fun_val = 2.698525
iter_number =  16 norm_grad = 0.006870 fun_val = 2.698520
iter_number =  17 norm_grad = 0.003146 fun_val = 2.698519
iter_number = 

(array([-0.62746978, -0.10556117,  0.08648754,  0.00125003,  0.06208885,
        -0.17584401, -0.02114735, -0.10405349, -0.11558102, -0.01649834]),
 2.6985151424269254)